version: '3.8'

services:
  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0
    container_name: fortalecesuas-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_secure_password}
      MYSQL_DATABASE: ${DB_NAME:-sistema_assistencia}
      MYSQL_USER: ${DB_USER:-cras_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-cras_secure_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - fortalecesuas-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fortalecesuas-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000

      # Database
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${DB_USER:-cras_user}
      DB_PASSWORD: ${DB_PASSWORD:-cras_secure_password}
      DB_NAME: ${DB_NAME:-sistema_assistencia}

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-1h}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}

      # Security
      CSRF_SECRET: ${CSRF_SECRET}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000}

      # Rate Limiting
      AUTH_RATE_MAX: ${AUTH_RATE_MAX:-10}
      API_RATE_MAX: ${API_RATE_MAX:-100}

      # Session
      SESSION_SECRET: ${SESSION_SECRET}
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./backups:/app/backups
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fortalecesuas-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx (Proxy Reverso - Opcional)
  nginx:
    image: nginx:alpine
    container_name: fortalecesuas-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - fortalecesuas-network
    profiles:
      - with-nginx

volumes:
  mysql_data:
    driver: local

networks:
  fortalecesuas-network:
    driver: bridge
